collections:
  authors:
    output: true
  talks:
  skills:
  experience:
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post_minima"
  - scope:
      path: ""
    values:
      layout: "default_minima"
title: Octavio Garbarino
subtitle: Engineering Manager
Author: Octavio Garbarino
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Octavio Garbarino personal website, in which there is his resume some useful information. Octavio is a Software Developer, Technical Lead, Engineering Manager and meetup speaker. Keep in touch!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oti.noroof.dev/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: octaviogarbet
github_username:  octaviogarbet
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag